Extract Action Mailer initializer to `rails g tiu:app:setup` so it isn't present until after bundling and running `rails app:create_dotenv`.
This avoids an error during `rails new example --template` in between bundling and running our generators:

       rails  javascript:install:esbuild
         rvm  Executing :rails in RVM gemset ruby-3.2.2@caboose
rails aborted!
KeyError: key not found: "SMTP_USER"
/Users/ahoyt/code/eita/caboose/config/initializers/action_mailer.rb:24:in `fetch'